name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    timeout-minutes: 30

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew || true

      - name: Compilar APK
        run: ./gradlew :app:assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: geator-mensagens-apk
          path: app/build/outputs/apk/debug/app-debug.apk
